import type { Metadata } from 'next';
import { ThemeProvider } from '@/components/theme-provider';

import './globals.css';

import { Roboto, JetBrains_Mono } from 'next/font/google';


const jetBrainsMono = JetBrains_Mono({
    weight: '400',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Next',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en' suppressHydrationWarning>
            <body className={`${jetBrainsMono.className} antialiased`}>
                <ThemeProvider
                    attribute='class'
                    defaultTheme='system'
                    enableSystem
                    disableTransitionOnChange>
                    {children}
                </ThemeProvider>
            </body>
        </html>
    );
}
